<div class="container py-5">
  <div class="row">
    <div class="col">
      <% if @contact.errors.any? %>
        <%= @contact.errors.count %>件のエラーが発生しました
        <ul>
          <% @contact.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>

  <h4 class="m-4 font-weight-bold"><strong>お問い合わせ</strong></h4>
  <div class="flash">
    <%= flash[:notice] %>
  </div>
  <div class="row">
    <div class="col">
      <%= form_with model: @contact, url: contacts_confirm_path(reply_id: params[:reply_id]) do |f| %>
        <div>
          <%= f.label :subject, '件名' %>
          <%= f.text_field :subject, autofocus: true, class: 'form-control' %>
        </div>

        <div>
          <%= f.label :content, 'お問い合わせ内容' %>
          <%= f.text_area :content, size: '10x10', class: 'form-control' %>
        </div>

        <div>
          <%= f.submit '入力内容確認', class: 'btn btn-outline-dark mt-3' %>
        </div>
      <% end %>
    </div>
  </div>
</div>